version: 2
jobs:
    test-3.7: &test-template
        docker:
            - image: circleci/python:3.7.1
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: "Install Python requirements"
                command: |
                    sudo pip install -Ur requirements-dev.txt
                    sudo python setup.py install
            - run:
                name: "Run tests"
                command: pytest --cov=chaospy chaospy tests
            - run:
                name: "Coverage report"
                command: codecov
    test-2.7:
        <<: *test-template
        docker:
            - image: circleci/python:2.7.15
workflows:
    version: 2
    test:
        jobs:
            - test-3.7
            - test-2.7
