version: 2
jobs:
    build:
        working_directory: ~/chaospy
        docker:
            - image: circleci/python:3.6.2
        steps:
            - checkout
            - restore_cache:
                key: reqs-{{ checksum "requirements.txt" }}
            - run:
                name: "Install Python requirements"
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip3 install -U pip
                    pip3 install -Ur requirements-dev.txt
                    python3 setup.py develop
            - save_cache:
                key: reqs-{{ checksum "requirements.txt" }}
                paths:
                    - venv
            - run:
                name: "Run tests"
                command: |
                    . venv/bin/activate
                    pytest --cov=chaospy
            - run:
                name: "Run sphinx"
                command: |
                    . venv/bin/activate
                    mkdir -p doc/.html
                    sphinx-build --keep-going -n -W -a -E -vv --color -j auto doc/.html doc/
            - run:
                name: "Coverage report"
                command: |
                    . venv/bin/activate
                    codecov
